# Generated by Django 4.2.19 on 2025-03-19 23:05

from django.db import migrations, models
import tdapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('check_in', models.DateField(validators=[tdapp.models.validate_date])),
                ('check_out', models.DateField(validators=[tdapp.models.validate_date])),
                ('guests', models.PositiveIntegerField()),
            ],
        ),
    ]
