version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
 
  pre_build:
    commands:
      - python --version
      #- pylint $(find $CODEBUILD_SRC_DIR -name "*.py") --fail-under=6 || true
      #- pylint --exit-zero $CODEBUILD_SRC_DIR/*.py
      - pylint --exit-zero $CODEBUILD_SRC_DIR/tdsystem/*.py
      - pylint --exit-zero $CODEBUILD_SRC_DIR/tdapp/*.py
      - echo "Running database migrations..."
      - python manage.py migrate
artifacts:
  files:
    - '**/*'