version: 0.2
env:
  secrets-manager:
    LOGIN: venkadesh_sonar:LOGIN
    HOST: venkadesh_sonar:HOST
    Organization: venkadesh_sonar:Organization
    Project: venkadesh_sonar:Project
phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - yum update -y
      - yum install -y jq unzip
      - python -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - chmod +x sonar-scanner-5.0.1.3006-linux/bin/*
      - export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin
  pre_build:
    commands:
      - python --version
      - java -version
      - sonar-scanner --version
  build:
    commands:
      - echo "Waiting for SonarCloud automatic analysis to complete..."
      - sleep 60  # Adjust based on expected time for analysis completion
      - echo "Checking Quality Gate status..."
      - curl -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
      - cat result.json
      - |
        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
          echo "❌ Quality Gate failed"
          exit 1
        else
          echo "✅ Quality Gate passed"
        fi
artifacts:
  files:
    - '**/*'